/*  This file is part of Project braxel.
 *
 *  Project braxel is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  Project braxel is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with Project braxel. If not, see <http://www.gnu.org/licenses/>. */
/* This file was generated by build.sh at 01/12/17 14:54:11 */
#ifndef LIBBRAXEL_H
#define LIBBRAXEL_H

#include <stdio.h>
#include <png.h>


/* Exported from ./definitions/brxexport.h */

/* Exported from ./xmacro/brxxmodes.h */
#define BRX_X_MODES_LIST     \
    BRX(DST,  brx_mode_dst ) \
    BRX(SRC,  brx_mode_src ) \
    BRX(NDST, brx_mode_ndst) \
    BRX(NSRC, brx_mode_nsrc) \
    BRX(OR,   brx_mode_or  ) \
    BRX(AND,  brx_mode_and ) \
    BRX(XOR,  brx_mode_xor ) \
    BRX(NOR,  brx_mode_nor ) \
    BRX(NAND, brx_mode_nand)


/* Exported from ./xmacro/brxxerrors.h */
#define BRX_X_ERRORS_LIST \
    /*        Name                Code              Description              */ \
    /* No error                                                              */ \
    BRX(SUCCESS             , (0x00),        "Successfull                    ") \
    /* System general errors                                                 */ \
    BRX(SYSTEM_GENERALERROR , (0x01),        "Generic error                  ") \
    BRX(SYSTEM_MISUSEOFBLTNS, (0x02),        "Misuse of shell built-ins      ") \
    /* Memory errors                                                         */ \
    BRX(USER_BADALLOC       , (0x10 + 0x01), "Memory allocation failed       ") \
    /* Pointer errors                                                        */ \
    BRX(USER_BADPOINTER     , (0x20 + 0x01), "Bad pointer provided           ") \
    /* Geometry errors                                                       */ \
    BRX(USER_BADWIDTH       , (0x30 + 0x01), "Bad width provided             ") \
    BRX(USER_BADHEIGHT      , (0x30 + 0x02), "Bad height provided            ") \
    BRX(USER_BADX           , (0x30 + 0x03), "Bad x provided                 ") \
    BRX(USER_BADY           , (0x30 + 0x04), "Bad y provided                 ") \
    /* Filesystem errors                                                     */ \
    BRX(USER_BADFILE        , (0x40 + 0x01), "Bad file provided              ") \
    BRX(USER_BADPNGFILE     , (0x40 + 0x02), "Bad PNG file provided          ") \
    /* System errors                                                         */ \
    BRX(SYSTEM_CANNOTEXECUTE, (0x7E),        "Command invoked cannot execute ") \
    BRX(SYSTEM_NOTFOUND     , (0x7F),        "Command not found              ") \
    BRX(SYSTEM_INVALIDEXIT  , (0x80),        "Invalid argument to exit       ") \
    /* System signals                                                        */ \
    BRX(SYSTEM_SIGHUP       , (0x80 + 0x01), "Hangup                         ") \
    BRX(SYSTEM_SIGINT       , (0x80 + 0x02), "Interrupt                      ") \
    BRX(SYSTEM_SIGQUIT      , (0x80 + 0x03), "Quit                           ") \
    BRX(SYSTEM_SIGILL       , (0x80 + 0x04), "Illegal Instruction            ") \
    BRX(SYSTEM_SIGTRAP      , (0x80 + 0x05), "Trace/Breakpoint Trap          ") \
    BRX(SYSTEM_SIGABRT      , (0x80 + 0x06), "Abort                          ") \
    BRX(SYSTEM_SIGEMT       , (0x80 + 0x07), "Emulation Trap                 ") \
    BRX(SYSTEM_SIGFPE       , (0x80 + 0x08), "Arithmetic Exception           ") \
    BRX(SYSTEM_SIGKILL      , (0x80 + 0x09), "Killed                         ") \
    BRX(SYSTEM_SIGBUS       , (0x80 + 0x0A), "Bus Error                      ") \
    BRX(SYSTEM_SIGSEGV      , (0x80 + 0x0B), "Segmentation Fault             ") \
    BRX(SYSTEM_SIGSYS       , (0x80 + 0x0C), "Bad System Call                ") \
    BRX(SYSTEM_SIGPIPE      , (0x80 + 0x0D), "Broken Pipe                    ") \
    BRX(SYSTEM_SIGALRM      , (0x80 + 0x0E), "Alarm Clock                    ") \
    BRX(SYSTEM_SIGTERM      , (0x80 + 0x0F), "Terminated                     ") \
    BRX(SYSTEM_SIGUSR1      , (0x80 + 0x10), "User Signal 1                  ") \
    BRX(SYSTEM_SIGUSR2      , (0x80 + 0x11), "User Signal 2                  ") \
    BRX(SYSTEM_SIGCHLD      , (0x80 + 0x12), "Child Status                   ") \
    BRX(SYSTEM_SIGPWR       , (0x80 + 0x13), "Power Fail/Restart             ") \
    BRX(SYSTEM_SIGWINCH     , (0x80 + 0x14), "Window Size Change             ") \
    BRX(SYSTEM_SIGURG       , (0x80 + 0x15), "Urgent Socket Condition        ") \
    BRX(SYSTEM_SIGPOLL      , (0x80 + 0x16), "Socket I/O Possible            ") \
    BRX(SYSTEM_SIGSTOP      , (0x80 + 0x17), "Stopped (signal)               ") \
    BRX(SYSTEM_SIGTSTP      , (0x80 + 0x18), "Stopped (user)                 ") \
    BRX(SYSTEM_SIGCONT      , (0x80 + 0x19), "Continued                      ") \
    BRX(SYSTEM_SIGTTIN      , (0x80 + 0x1A), "Stopped (tty input)            ") \
    BRX(SYSTEM_SIGTTOU      , (0x80 + 0x1B), "Stopped (tty output)           ") \
    BRX(SYSTEM_SIGVTALRM    , (0x80 + 0x1C), "Virtual Timer Expired          ") \
    BRX(SYSTEM_SIGPROF      , (0x80 + 0x1D), "Profiling Timer Expired        ") \
    BRX(SYSTEM_SIGXCPU      , (0x80 + 0x1E), "CPU time limit exceeded        ") \
    BRX(SYSTEM_SIGXFSZ      , (0x80 + 0x1F), "File size limit exceeded       ") \
    BRX(SYSTEM_SIGWAITING   , (0x80 + 0x20), "All LWPs blocked               ") \
    BRX(SYSTEM_SIGLWP       , (0x80 + 0x21), "VI Interrupt for T. Library    ") \
    BRX(SYSTEM_SIGAIO       , (0x80 + 0x22), "Asynchronous I/O               ") \
                                                                                \
    BRX(SYSTEM_OUTOFRANGE   , (0xFF),        "Exit status unknown            ") \
    /* Maximum is 255, as this index will be sent to exit() function         */


/* Exported from ./definitions/brxtypes.h */
#define BRX_BRAILLE_WIDTH   (2)
#define BRX_BRAILLE_HEIGHT  (4)
#define BRX_BRAILLE_COUNT (256)
#define BRX_BRAILLE_BITS (BRX_BRAILLE_WIDTH * BRX_BRAILLE_HEIGHT)

typedef   signed      char  i8;
typedef unsigned      char  u8;
typedef   signed short int i16;
typedef unsigned short int u16;
typedef   signed       int i32;
typedef unsigned       int u32;
#define  U8_MIN (0)
#define U16_MIN (0)
#define U32_MIN (0)

#define  U8_MAX (0xFFU)
#define U16_MAX (0xFFFFU)
#define U32_MAX (0xFFFFFFFFU)

#define  I8_MIN (-128)
#define I16_MIN (-32768)
#define I32_MIN (-2147483648)

#define  I8_MAX (127)
#define I16_MAX (32767)
#define I32_MAX (2147483647)

typedef struct
{
    i32 x;
    i32 y;
} BrxPoint;

typedef struct
{
    u32 w;
    u32 h;
} BrxSize;

typedef struct
{
    BrxSize size;
    u8 *    data;
} BrxPicture;

#define BRX(NAME, CODE, DESC) BRX_ERROR_ ## NAME = (CODE),
typedef enum
{
    BRX_X_ERRORS_LIST
    BRX_ERROR_LAST
} BrxError;
#undef BRX

#define BRX(NAME, FUNC) BRX_MODE_ ## NAME,
typedef enum
{
    BRX_X_MODES_LIST
    BRX_MODE_LAST
} BrxMode;
#undef BRX


/* Exported from ./graph/brxgraph.h */
BrxError BrxPictureDraw    (BrxPicture  * picture, FILE * handler);
BrxError BrxPicturePixelSet(BrxPicture  * picture, BrxPoint * point, u8   value);
BrxError BrxPicturePixelGet(BrxPicture  * picture, BrxPoint * point, u8 * value);
BrxError BrxPictureMap     (BrxPicture  * dst, BrxPicture * src, BrxPoint * point, BrxMode mode);

/* Exported from ./graph/brxpng.h */
BrxError BrxPictureFromPNG (BrxPicture ** picture, char * filename);

/* Exported from ./help/brxhelp.h */
char * BrxErrorDescription(BrxError error);

/* Exported from ./definitions/brxcheck.h */

/* Exported from ./definitions/brxcolours.h */

/* Exported from ./base/brxbase.h */
BrxError BrxInit(void);
BrxError BrxPictureCreate  (BrxPicture ** picture, BrxSize *size);
BrxError BrxPictureDestroy (BrxPicture ** picture);

/* Exported from ./alphabet/brxalphabet.h */

#endif /* LIBBRAXEL_H */
